### PR TITLE
Add telemetry pings to better understand Firebase lifecycle

### PR DESCRIPTION
**Pull request by cnevinc**
We want this data cause we want to verify when below timing, FIrebase RemoteConfing has completed fetching or not:
- The users see onboarding page
- The users finish onboarding page
- The users see the first level toolbar of HomeFragment-
- The users see the second level toolbar of HomeFragment
- The users see the first level toolbar of BrowserFragment.
- The users see the second level toolbar of BrowserFragment.

Confirmed with @elin-moco 
1. We only need to record the first fetch when the app is launched. 
2. We only need to record the ping for new users only (in case data mixed up)

### CODE REVIEW

**Comment by elin-moco** [comment]
Note that we only need to record the ping for new users only (in case data mixed up)

**Comment by cnevinc** [comment]
@elin-moco Please help review the pings
https://github.com/mozilla-tw/FirefoxLite/pull/3081/files#diff-833b6d7070c26b0f7548f4ffdc70eb8eR3

**Comment by cnevinc** [comment]
I need some tweeks in local.  Close this temporarily,

**Comment by cnevinc** [comment]
> We want this data cause we want to verify when below timing, FIrebase RemoteConfing has completed fetching or not:
> 
> * The users see onboarding page
> * The users finish onboarding page
> * The users see the first level toolbar of HomeFragment
This timing is almost the same as "The users finish onboarding page"
> * The users see the second level toolbar of HomeFragment
When "The users see the first level toolbar of HomeFragment", the second level is already inflated. so the timing is the same.
> * The users see the first level toolbar of BrowserFragment.
BrowserFragment initialized earlier than HomeFragment, so this can be skipped.
> * The users see the second level toolbar of BrowserFragment.
ditto
> 
> Confirmed with @elin-moco
> 
> 1. We only need to record the first fetch when the app is launched.
> 2. We only need to record the ping for new users only (in case data mixed up)

**Pull request closed without merging**
