### PR TITLE
Privately/multi tabs

### PR DESCRIPTION
**Pull request by walkingice**
This PR tries to enable multi-tabs feature in Private Mode

### CODE REVIEW

**Comment by mTwTm** [comment]
org.mozilla.focus.tabs.tabtray.TabTrayPresenterTest > viewReady_showFocusedTab FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at TabTrayPresenterTest.kt:60

**Comment by walkingice** [comment]
I rebased to master for fixing conflicts, @cnevinc could you help me to solve the Test issue?

**Comment by mTwTm** [comment]
* What went wrong:
Execution failed for task ':app:testFocusWebkitDebugUnitTest'.
> There were failing tests. See the report at: file:///bitrise/src/app/build/reports/tests/testFocusWebkitDebugUnitTest/index.html

**Comment by mTwTm** [comment]
We might be able to take this in the next sprint, which will start from next Monday

**Comment by cnevinc** [comment]
> I rebased to master for fixing conflicts, @cnevinc could you help me to solve the Test issue?

the test fails because you now allow 0 tabs. We need UX to confirm before we can land this. Or have pref in front of this behaviour.

**Comment by cnevinc** [comment]
I have some extra work in #3328.
Feel free to pick that and land this PR, or use that one, whatever works for you.

**Comment by cnevinc** [comment]
I'm assigned to other tasks. So I'll pause the work here.

**Pull request closed without merging**
